# Generated by Django 5.0.1 on 2024-02-06 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_updated_date_alter_postfile_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 15, 33, 11, 839405)),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 15, 33, 11, 839405)),
        ),
    ]
