# Generated by Django 5.0.1 on 2024-02-07 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_updated_date_alter_postfile_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_read_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 17, 7, 53, 935707)),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 17, 7, 53, 935707)),
        ),
    ]
