# Generated by Django 5.0.1 on 2024-02-07 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_post_read_count_alter_post_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_preview_image',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 17, 13, 42, 775093)),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 17, 13, 42, 775093)),
        ),
    ]
