# Generated by Django 5.0.1 on 2024-02-08 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_updated_date_alter_postfile_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_preview_image',
        ),
        migrations.AddField(
            model_name='postfile',
            name='preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 5, 12, 266183)),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 5, 12, 266183)),
        ),
    ]
