# Generated by Django 5.0.1 on 2024-02-08 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_post_preview_image_postfile_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 13, 3, 31, 906137)),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 13, 3, 31, 906137)),
        ),
    ]
