# Generated by Django 5.0.1 on 2024-02-12 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0015_alter_post_updated_date_alter_postfile_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 12, 12, 5, 6, 877469)
            ),
        ),
        migrations.AlterField(
            model_name="postfile",
            name="updated_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 12, 12, 5, 6, 877469)
            ),
        ),
    ]
