# Generated by Django 5.0.1 on 2024-02-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='memberfile',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='memberfile',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
