# Generated by Django 5.0.1 on 2024-02-06 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_create_date_member_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 13, 46, 6, 507359)),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 13, 46, 6, 507359)),
        ),
    ]
