# Generated by Django 5.0.1 on 2024-02-13 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_member_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
