# Generated by Django 4.2.4 on 2023-08-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-id']},
        ),
    ]
